namespace PretClient
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Int32 MyProperty();
        void MyProperty(Int32 value);
        void myButton_Click(Windows.Foundation.IInspectable const& sender, Microsoft.UI.Xaml.RoutedEventArgs const& args);
    }
}
